import "@/styles/globals.css";
import { Canvas } from "@react-three/fiber";
import { ScrollControls } from "@react-three/drei";
import type { AppProps } from "next/app";
import { Bebas_Neue } from "next/font/google";
import Head from "next/head";

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--bebas",
});
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Dev By Nate | Dragon Farm </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${bebas.variable} h-screen`}>
        <Canvas>
          <ScrollControls pages={3} damping={0.1}>
            <Component {...pageProps} />
          </ScrollControls>
        </Canvas>
      </main>
    </>
  );
}
